COBRAAzure/Controllers/CustomerController.cs
using COBRA.Models;
using COBRAAzure;
using Entity.Model.CustomerModels;
using Entity.UnitOfWork;
using Entity.UnitOfWork.CustomerRepo;
using Grid.Mvc.Ajax.GridExtensions;
using Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace COBRA.MVC
{
    public class CustomerController : CustomerControllerBase
    {
        public CustomerController(ICustomerRepository repositoryInstance)
        {
            this._repositoty = repositoryInstance;
        }

        public CustomerController()
        {            
            _uow = new CustomerUnitOfWork();            
            this._repositoty = new CustomerRepository(_uow);
            this._codeListrepositoty = new CodeListDetailRepository(_uow);
        }

        public ActionResult Index()
        {
            return View();
        }
        // GET: /Customer/Create
        public ActionResult Registration(long? pCustomerID)
        {
            try
            {
                Customer customer = null;

                if (!pCustomerID.HasValue)
                {
                    this.BuildViewBagCollection(customer);
                    return View();
                }
                
                if (pCustomerID.HasValue
                    && pCustomerID.Value == 0)
                {
                    customer = this._repositoty.CreateCustomer();                                 
                }
                else
                {
                    customer = this._repositoty.GetCustomerByID(pCustomerID.Value);                    
                }

                this.BuildViewBagCollection(customer);
                return View(customer);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View();
        }

        public ActionResult CreateCustomerAttribute(int index)
        {
            try
            {
                CustomerAttribute attribute = this._repositoty.CreateCustomerAttribute();
                this.BuildViewBagCollection(attribute);
                ViewData["AttributeIndex"] = index;
                return PartialView("_CustomerAttribute", attribute);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return PartialView("_CustomerAttribute", null);
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration(Customer customer, string[] chkBillingOptions)
        {
            try
            {                
                this.CreateCustomerBillingOptionsXRef(customer, chkBillingOptions);
                this.ExecutePreSaveConditions(customer, this._repositoty, customer.CustomerAttributes.ToList());

                if(!this.IsModelValid)
                    return View(customer);

                if (customer.RecordVersion == 0) // New Customer
                {
                    this._repositoty.AddCustomer(customer);
                }
                else
                {
                    this._repositoty.UpdateCustomer(customer);
                }

                int status = this._repositoty.SaveChanges();
                if (status == ApplicationKeys.SaveUnsucessful)
                {
                    // Save should not unsucessful as the validations are done prior to invoking SaveChanges method 
                    this.BindValidationErrors(customer);
                    return View(customer);
                }
                else
                {
                    return View("_CustomerSuccess", customer);
                }             
            }
            catch(Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }    
        
            return View(customer);
        }

        public ActionResult Details(long pCustomerID)
        {
            Customer customer = this._repositoty.GetCustomerByID(pCustomerID);
            return View(customer);
        }
               
        [AllowAnonymous]
        public ActionResult GetDataForPDF()
        {
            ViewBag.IsModalDialog = false;
            List<Customer> customers = this._repositoty.GetCustomers();
            
            return View("Customer/_CustomersPDF", customers);
        }

        #region Search Customers

        public ActionResult SearchResultsToPDF()
        {
            List<Customer> customers = new List<Customer>();
            
            if (Session["searchCriteria"] != null)
            {
                CustomerSearchCriteriaModel serachCriteria = (CustomerSearchCriteriaModel)Session["searchCriteria"];
                customers = this._repositoty.GetCustomersBySearchCriteria(serachCriteria);                                           
            }

            string pdfFileName = "CustomerSearchResults_" + DateTime.Now.ToShortDateString() + ".pdf";            
            return this.ViewPdf("", "Customer/_CustomersPDF", customers, pdfFileName);
            //ViewAsPdf pdf = new ViewAsPdf("Customer/_CustomersPDF", customers);
            //pdf.FileName = "CustomerSearchResults_" + DateTime.Now.ToShortDateString() + ".pdf";
            //pdf = GenericHelpers.Instance.SetPDFProperties(pdf);
            //return pdf;

        }

        public ActionResult SearchCustomer()
        {
            return View("Search/_SearchCustomer", new CustomerSearchCriteriaModel());
        }

        public ActionResult GetDefaultSearchResults(CustomerSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            AjaxGrid<Customer> grid = GetDefaultAjaxGrid<Customer>();
            return View("Search/_CustomerSearchResults", grid);
        }

        public JsonResult GetSearchResults(CustomerSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            Session["searchCriteria"] = searchCriteria;
            AjaxGrid<Customer> grid = GetAjaxGridByList<Customer>(this._repositoty.GetCustomersBySearchCriteria(searchCriteria));
            return Json(new { Html = grid.ToJson("Search/_CustomerSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSearchResultsPaged(CustomerSearchCriteriaModel searchCriteria, int? page)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Customer> grid = GetAjaxGridByList<Customer>(this._repositoty.GetCustomersBySearchCriteria(searchCriteria), page.HasValue ? page.Value : 1, 5);
            return Json(new { Html = grid.ToJson("Search/_CustomerSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        #endregion
     
        public ActionResult DisplayCustomerInfo(long pCustomerID)
        {
            return View("Customer/_CustomerInfoDisplay", this._repositoty.GetCustomerByID(pCustomerID));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._repositoty.Dispose();                
            }
            base.Dispose(disposing);
        }
	}
}

COBRAAzure/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entity.ProductModels;
using Entity.UnitOfWork.ProductRepo;
using Entity.UnitOfWork;
using Infrastructure;
using COBRA.Models;
using Grid.Mvc.Ajax.GridExtensions;

namespace COBRA.MVC.Controllers
{
    public class ProductController : ProductControllerBase
    {
        public ProductController(IProductRepository repositoryInstance)
        {
            this._repositoty = repositoryInstance;
        }

        public ProductController()
        {
            _uow = new ProductUnitOfWork();
            this._repositoty = new ProductRepository(_uow);
            this._codeListrepositoty = new CodeListDetailRepository(_uow);
        }

        // GET: /Product/Create
        public ActionResult CreateOrEdit(long? pProductID)
        {
            Product product = null;
            ViewBag.Caption = string.Empty;

            if (!pProductID.HasValue)
            {
                this.BuildViewBagCollection(null);
                return View();
            }
            else if (pProductID.Value == 0)
            {
                product = this._repositoty.CreateProduct();
                ViewBag.Caption = "ADD PRODUCT - " + product.ProductID.ToString();
            }
            else
            {
                product = this._repositoty.GetProductByID(pProductID.Value);
                ViewBag.Caption = "MODIFY PRODUCT - " + product.ProductID.ToString();
            }

            this.BuildViewBagCollection(product);            
            return View(product);                        
        }

        // POST: /Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(Product product)
        {
            try
            {
                this.ExecutePreSaveConditions<Product>(product, this._repositoty, null);                

                if (!this.IsModelValid)
                    return View(product);

                if (product.RecordVersion == 0)
                {
                    this._repositoty.AddProduct(product);
                }
                else
                {
                    product = this._repositoty.UpdateProduct(product);
                }

                int saveStatus = this._repositoty.SaveChanges();

                if (saveStatus != ApplicationKeys.SaveUnsucessful)
                    return View("_ProductSuccess");                

            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(product);         
        }

        public ActionResult Details(long pProductID)
        {
            Product product = this._repositoty.GetProductByID(pProductID);
            return View(product);
        }

        #region Search Products

        public ActionResult SearchProduct()
        {
            return View("Search/_SearchProduct", new ProductSearchCriteriaModel());
        }

        public ActionResult GetDefaultProductSearchResults(ProductSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            AjaxGrid<Product> grid = GetDefaultAjaxGrid<Product>();
            return View(GetProductSearchResultsViewName(searchCriteria), grid);
        }

        public JsonResult GetProductSearchResults(ProductSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Product> grid = GetAjaxGridByList<Product>(this._repositoty.GetProductsBySearchCriteria(searchCriteria));
            return Json(new { Html = grid.ToJson(GetProductSearchResultsViewName(searchCriteria), this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductSearchResultsPaged(ProductSearchCriteriaModel searchCriteria, int? page)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Product> grid = GetAjaxGridByList<Product>(this._repositoty.GetProductsBySearchCriteria(searchCriteria), page.HasValue ? page.Value : 1, 5);
            return Json(new { Html = grid.ToJson(GetProductSearchResultsViewName(searchCriteria), this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Search Discount

        public ActionResult SearchDiscount()
        {
            return View("Search/_SearchDiscount", new DiscountSearchCriteriaModel());
        }
     
        public ActionResult GetDefaultDiscountSearchResults(DiscountSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            AjaxGrid<Discount> grid = GetDefaultAjaxGrid<Discount>();
            return View("Search/_DiscountSearchResults", grid);
        }

        public JsonResult GetDiscountSearchResults(DiscountSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Discount> grid = GetAjaxGridByList<Discount>(this._repositoty.GetDiscountsBySearchCriteria(searchCriteria));
            return Json(new { Html = grid.ToJson("Search/_DiscountSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDiscountSearchResultsPaged(DiscountSearchCriteriaModel searchCriteria, int? page)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Discount> grid = GetAjaxGridByList<Discount>(this._repositoty.GetDiscountsBySearchCriteria(searchCriteria), page.HasValue ? page.Value : 1, 5);
            return Json(new { Html = grid.ToJson("Search/_DiscountSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        #endregion


        public ActionResult Discount(int? pDiscountID)
        {
            try
            {
                Discount discount = null;

                if (!pDiscountID.HasValue)
                {
                    return View();
                }
                else if (pDiscountID.Value == 0)
                {
                    discount = this._repositoty.CreateDiscount();                    
                }
                else
                {
                    discount = this._repositoty.GetDiscountByID(pDiscountID.Value);
                }

                base.BuildViewBagCollection(discount);                
                return View(discount);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Discount(Discount discount)
        {
            try
            {
                this.ExecutePreSaveConditions(discount, this._repositoty, discount.DiscountDetailXRefs.ToList());
                
                if (!this.IsModelValid)
                    return View(discount);

                if (discount.RecordVersion == 0)
                    this._repositoty.AddDiscount(discount);
                else
                    this._repositoty.UpdateDiscount(discount);

                int saveStatus = this._repositoty.SaveChanges();

                if (saveStatus == ApplicationKeys.SaveUnsucessful)
                    this.BindValidationErrors(discount);
                else
                    return View("_DiscountSuccess");

            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(discount);
        }

        public ActionResult CreateDiscountDetailXRef(int index)
        {
            try
            {
                DiscountDetailXRef discountDetailXRef = this._repositoty.CreateDiscountDetailXRef();
                ViewData["DiscountDetailXRefIndex"] = index;
                base.BuildViewBagCollection(discountDetailXRef);
                return PartialView("_DiscountDetailXRef", discountDetailXRef);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return PartialView("_DiscountDetailXRef", null);
        }

        public ActionResult DiscountDetails(int pDiscountID)
        {
            Discount discount = this._repositoty.GetDiscountByID(pDiscountID);
            return View(discount);
        }

     
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._repositoty.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetProductSearchResultsViewName(ProductSearchCriteriaModel searchCriteria)
        {
            string viewName = "Search/_ProductSearchResults";

            if (searchCriteria.IsContractProductSearch)
            {
                viewName = "Search/_ProductContractSearchResults";
            }
          
            return viewName;
        }
    }
}

COBRAAzure/Views/Shared/Search/_CustomerSearchResults.cshtml
@using GridMvc.Html
@using GridMvc.Sorting
@model Grid.Mvc.Ajax.GridExtensions.AjaxGrid<Entity.Model.CustomerModels.Customer>

@{
    Layout = null;
}


@if ((bool)ViewBag.IsModalDialog)
{
    @Html.Grid(Model).Named("customerSearchResultsGrid").Columns(columns =>
    {
    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => @<a href="javascript:void();" onclick="RefreshCustomer('@o.CustomerID', '@o.CustomerNo');">Select</a>);
        columns.Add(model => model.CustomerNo).Titled("Customer No");
        columns.Add(model => model.LastName).Titled("Last Name");
        columns.Add(model => model.FirstName).Titled("First Name");
        columns.Add(model => model.Email).Titled("Email");
        columns.Add(model => model.Mobile).Titled("Mobile");

    }).Selectable(true).Sortable(true).Filterable(true).WithPaging(Infrastructure.ApplicationKeys.PageSize)
}
else
{
    @Html.Grid(Model).Named("customerSearchResultsGrid").Columns(columns =>
    {
    columns.Add(model => model.CustomerNo).Titled("Customer No");
    columns.Add(model => model.LastName).Titled("Last Name");
    columns.Add(model => model.FirstName).Titled("First Name");
    columns.Add(model => model.Email).Titled("Email");
    columns.Add(model => model.Mobile).Titled("Mobile");
    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => @<a href="javascript:void();" onclick="EditCustomer('@o.CustomerID');">Edit</a>);
    columns.Add()
      .Encoded(false)
      .Sanitized(false)
      .SetWidth(30)
      .RenderValueAs(o => @<a href="javascript:void();" onclick="ViewCustomer('@o.CustomerID');">View</a>);

    }).Selectable(true).Sortable(true).Filterable(true).WithPaging(Infrastructure.ApplicationKeys.PageSize)
    }


    
    

COBRAAzure/Views/Shared/Search/_SearchCustomer.cshtml
@model  COBRA.Models.CustomerSearchCriteriaModel
@{
    if (Model.IsModalDialog)
    {
        Layout = null;
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutSearch.cshtml";
    }

    ViewBag.Title = "Search Customer";
}

<div id="divCustomerSearch">    
    <div id="divCustomerSearchForm">
        @using (Html.BeginForm(null, null, null,  FormMethod.Post, new { id = "frmCustomerSearch" }))
        {
            @Html.Hidden("IsModalDialog", Model.IsModalDialog)
            
            <div class="divSubHeader">
                Search Customer
            </div>
            <div class="tablebox-border-max400">
                <div class="rowSmartLayout">
                    <div class="twoCol-1-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Last Name")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.SLastName)
                        </div>
                    </div>
                    <div class="twoCol-2-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("First Name")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.SFirstName)
                        </div>
                    </div>
                </div>

                <div class="rowSmartLayout">
                    <div class="twoCol-1-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Mobile #")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.SMobile)
                        </div>
                    </div>
                    <div class="twoCol-2-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Email Address #")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.SEmail)
                        </div>
                    </div>
                </div>

                <div class="rowSmartLayout">
                    <div class="twoCol-1-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Area / Address")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.SAddress)
                        </div>
                    </div>
                    <div class="twoCol-2-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Unique #")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.SCustomerNo)
                        </div>
                    </div>
                </div>
            </div>
             
            <div class="divButton-right">      
                <button name="btnSearch" id="btnSearch" type="submit"><i class="fa fa-search"></i>  Search</button>                          
            </div>                                          
        }
    </div>

    <div id="divCustomerSearchResults" class="SearchResults">
        <div class="divButton-right">
            <a href="javascript:void();" onclick="ExportToPDF();">PDF</a>            
        </div> 
                                                 
        @{ Html.RenderAction("GetDefaultSearchResults", "Customer"); }
    </div>
</div>


<script language="javascript">
    $(document).ready(function () {
        
        var tempUrl = '@Url.Action("GetSearchResults", "Customer")';
        var tempUrlPaged = '@Url.Action("GetSearchResultsPaged", "Customer")';
        pageGrids.customerSearchResultsGrid.ajaxify({
            getPagedData: tempUrlPaged,
            getData: tempUrl,
            gridFilterForm: $('#frmCustomerSearch')
        });
    });

    var isCustomerSearchModalDialog = $("#IsModalDialog").val().toLowerCase();
                var divCustomerSearch = "divCustomerSearch";
                var divCustomerSearchResults = "divCustomerSearchResults";
                var frmCustomerSearch = "frmCustomerSearch";

    // Only if Search window has to open in Modal Dialog
    if (isCustomerSearchModalDialog == "true") {
        InitializeDialog(divCustomerSearch);
            }

         
            function OpenCustomerSearchDialog()
            {                
                //$("#" + frmCustomerSearch)[0].reset();
                //$("#" + divCustomerSearchResults).html("");
                OpenDialog(divCustomerSearch);
            }

            function CloseCustomerSearchDialog() {
                CloseDialog(divCustomerSearch);
            }

            function EditCustomer(tempCustomerID) {
                var tempUrl = '@Url.Action("Registration", "Customer", new { pCustomerID = -999 })';
                tempUrl = tempUrl.replace("-999", tempCustomerID);
                location.href = tempUrl;
            }

            function ViewCustomer(tempCustomerID) {
                var tempUrl = '@Url.Action("Details", "Customer", new { pCustomerID = -999 })';
                tempUrl = tempUrl.replace("-999", tempCustomerID);
                location.href = tempUrl;
            }

            function ExportToPDF() {
                var tempUrl = '@Url.Action("SearchResultsToPDF", "Customer")';                
                window.open(tempUrl, "_blank");                
            }       
    
</script>

COBRAAzure/Views/Shared/Search/_SearchDiscount.cshtml
@model  COBRA.Models.DiscountSearchCriteriaModel
@{
    if (Model.IsModalDialog)
    {
        Layout = null;
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutSearch.cshtml";
    }
}

<div id="divDiscountSearch">   
    <div id="divDiscountSearchForm">
        @using (Html.BeginForm(null, null, null, FormMethod.Post, new { id = "frmDiscountSearch" }))
        {
            @Html.Hidden("IsModalDialog", Model.IsModalDialog)

            <div class="divSubHeader">
                Search Product
            </div>

            <div class="tablebox-border-max400">
                <div class="rowSmartLayout">
                    <div class="twoCol-1-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Discount Name")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.DiscountName)
                        </div>
                    </div>
                </div>
            </div>

            <div class="divButton-right">
                <button name="btnSearch" id="btnSearch" type="submit"><i class="fa fa-search"></i>  Search</button>
            </div>          
        }
    </div>

    <div id="divDiscountSearchResults" class="SearchResults">
        @{ Html.RenderAction("GetDefaultDiscountSearchResults", "Product"); }
    </div>
</div>

<script language="javascript">

    $(document).ready(function () {

        var tempUrl = '@Url.Action("GetDiscountSearchResults", "Product")';
        var tempUrlPaged = '@Url.Action("GetDiscountSearchResultsPaged", "Product")';
        pageGrids.discountSearchResultsGrid.ajaxify({
            getPagedData: tempUrlPaged,
            getData: tempUrl,
            gridFilterForm: $('#frmDiscountSearch')
        });
    });

    var isDiscountSearchModalDialog = $("#IsModalDialog").val().toLowerCase();
    var divDiscountSearch = "divDiscountSearch";
    var divDiscountSearchResults = "divDiscountSearchResults";
    var frmDiscountSearch = "frmDiscountSearch";

    // Only if Search window has to open in Modal Dialog
    if (isDiscountSearchModalDialog == "true") {
        InitializeDialog(divDiscountSearch);
    }

    function OpenDiscountSearchDialog()
    {
       // $("#" + frmDiscountSearch)[0].reset();
        //$("#" + divDiscountSearchResults).html("");
        OpenDialog(divDiscountSearch);
    }

    function CloseDiscountSearchDialog() {
        CloseDialog(divDiscountSearch);
    }

    function EditDiscount(tempDiscountID) {
        var tempUrl = '@Url.Action("Discount", "Product", new { pDiscountID = -999 })';
        tempUrl = tempUrl.replace("-999", tempDiscountID);
        location.href = tempUrl;
    }

    function ViewDiscount(tempDiscountID) {
        var tempUrl = '@Url.Action("DiscountDetails", "Product", new { pDiscountID = -999 })';
        tempUrl = tempUrl.replace("-999", tempDiscountID);
        location.href = tempUrl;
    }

</script>

COBRAAzure/Views/Shared/Search/_SearchProduct.cshtml
@model  COBRA.Models.ProductSearchCriteriaModel
@{
    if (Model.IsModalDialog)
    {
        Layout = null;
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutSearch.cshtml";
    }
}

<div id="divProductSearch">
    <div id="divProductSearchForm">
        @using (Html.BeginForm(null, null, null, FormMethod.Post, new { id = "frmProductSearch" }))
            {
                @Html.Hidden("IsModalDialog", Model.IsModalDialog)
                @Html.Hidden("productContractTermTypeCodeID", Model.productContractTermTypeCodeID);
                @Html.Hidden("productCustomerID", Model.productCustomerID);
                @Html.Hidden("IsContractProductSearch", Model.IsContractProductSearch);

            <div class="divSubHeader">
                Search Product
            </div>

            <div class="tablebox-border-max400">
                <div class="rowSmartLayout">
                    <div class="twoCol-1-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.Label("Product Description")
                        </div>
                        <div class="CellControl">
                            @Html.TextBoxFor(model => model.ProductDescription)
                        </div>
                    </div>                    
                </div>
            </div>

            <div class="divButton-right">
                <button name="btnSearch" id="btnSearch" type="submit"><i class="fa fa-search"></i>  Search</button>
            </div>            
        }
    </div>

    <div id="divProductSearchResults" class="SearchResults">
        @{ Html.RenderAction("GetDefaultProductSearchResults", "Product"); }
    </div>
</div>

<script language="javascript">
    
    $(document).ready(function () {

        var tempUrl = '@Url.Action("GetProductSearchResults", "Product")';
        var tempUrlPaged = '@Url.Action("GetProductSearchResultsPaged", "Product")';
        pageGrids.productSearchResultsGrid.ajaxify({
            getPagedData: tempUrlPaged,
            getData: tempUrl,
            gridFilterForm: $('#frmProductSearch')
        });
    });

    var isProductSearchModalDialog = $("#IsModalDialog").val().toLowerCase();
    var divProductSearch = "divProductSearch";
    var divProductSearchResults = "divProductSearchResults";
    var frmProductSearch = "frmProductSearch";

    // Only if Search window has to open in Modal Dialog
    if (isProductSearchModalDialog == "true") {
        InitializeDialog(divProductSearch);
    }

    function OpenProductSearchDialog() {       
        OpenDialog(divProductSearch);
    }
   
    function CloseProductSearchDialog() {
        CloseDialog(divProductSearch);
    }

    function EditProduct(tempProductID) {
        var tempUrl = '@Url.Action("CreateOrEdit", "Product", new { pProductID = -999 })';
        tempUrl = tempUrl.replace("-999", tempProductID);
        location.href = tempUrl;
    }

    function ViewProduct(tempProductID) {
        var tempUrl = '@Url.Action("Details", "Product", new { pProductID = -999 })';
        tempUrl = tempUrl.replace("-999", tempProductID);
        location.href = tempUrl;
    }

</script>