COBRAAzure/Controllers/HomeController.cs
using Entity.Model.CustomerModels;
using Entity.ProductModels;
using Entity.UnitOfWork;
using Entity.UnitOfWork.CustomerRepo;
using Entity.UnitOfWork.ProductRepo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COBRAAzure.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {

            IUnitOfWork uow = new CustomerUnitOfWork();
            ICustomerRepository repo = new CustomerRepository(uow);
            List<Customer> customer = repo.GetCustomers();

            IUnitOfWork puow = new ProductUnitOfWork();
            IServiceRepository serviceRepo = new ServiceRepository(puow);
            List<Service> services = serviceRepo.GetServices();
            ViewBag.Message = "Your application accessed Customers" + customer.Count + " Services : " + services.Count;
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

COBRAAzure/Controllers/ReportController.cs
using COBRA.Models;
using Entity.UnitOfWork;
using Entity.UnitOfWork.ReportsRepo;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;

using System.Web.Mvc;
using System.Web.UI.DataVisualization.Charting;

namespace COBRAAzure.Controllers
{
    public class ReportController : Controller
    {
        protected IReportRepository _repositoty = null;
        protected IUnitOfWork _uow = null;

        public ReportController()
        {
            _uow = new CustomerUnitOfWork();
            this._repositoty = new ReportRepository(_uow);
        }

        public ActionResult CategoryWiseCustomerReport()
        {
            List<ReportItem<string, decimal>> reportItems = this._repositoty.CategoryWiseCustomerReport(); 
                                   
            Chart chart = new Chart();            
            ReportHelper.Instance.SetPieChartAttributes(chart, reportItems);
            ReportHelper.Instance.SetTitle(chart, "TOP Customers");
            ReportHelper.Instance.SetLegend(chart);
            ReportHelper.Instance.SetChartArea(chart, "TOP Customers");
            var returnStream = new MemoryStream();
            chart.ImageType = ChartImageType.Png;
            chart.SaveImage(returnStream);
            returnStream.Position = 0;
            return new FileStreamResult(returnStream, "image/png");
        }

        public ActionResult ProductWiseContractReport()
        {
            List<ReportItem<string, decimal>> reportItems = this._repositoty.ProductWiseContractReport();

            Chart chart = new Chart();
            ReportHelper.Instance.SetPieChartAttributes(chart, reportItems);
            ReportHelper.Instance.SetTitle(chart, "TOP Products");
            ReportHelper.Instance.SetLegend(chart);
            ReportHelper.Instance.SetChartArea(chart, "TOP Products");
            var returnStream = new MemoryStream();
            chart.ImageType = ChartImageType.Png;
            chart.SaveImage(returnStream);
            returnStream.Position = 0;
            return new FileStreamResult(returnStream, "image/png");
        }

        public ActionResult RegionWiseBillingReport()
        {
            List<ReportItem<string, decimal>> reportItems = this._repositoty.RegionWiseBillingReport();

            Chart chart = new Chart();
            ReportHelper.Instance.SetPieChartAttributes(chart, reportItems);
            ReportHelper.Instance.SetTitle(chart, "Revenue");
            ReportHelper.Instance.SetLegend(chart);
            ReportHelper.Instance.SetChartArea(chart, "Revenue");
            var returnStream = new MemoryStream();
            chart.ImageType = ChartImageType.Png;
            chart.SaveImage(returnStream);
            returnStream.Position = 0;
            return new FileStreamResult(returnStream, "image/png");
        }

        public ActionResult ContractStatusSplitupReport()
        {
            List<ReportItem<string, decimal>> reportItems = this._repositoty.ContractStatusSplitupReport();

            Chart chart = new Chart();
            ReportHelper.Instance.SetPieChartAttributes(chart, reportItems);
            ReportHelper.Instance.SetTitle(chart, "Contracts");
            ReportHelper.Instance.SetLegend(chart);
            ReportHelper.Instance.SetChartArea(chart, "Contracts");
            var returnStream = new MemoryStream();
            chart.ImageType = ChartImageType.Png;
            chart.SaveImage(returnStream);
            returnStream.Position = 0;
            return new FileStreamResult(returnStream, "image/png");
        }
    }
}

COBRAAzure/Views/Home/About.cshtml
@{
    Layout = null;
}



<style type="text/css">

    * {
        padding: 0;
        margin: 0;
    }

  
</style>


<p><input type='checkbox' class='checkbox' id="check01" /><label for="check01">Checkbox</label></p>
<p><input type='checkbox' class='checkbox' id="check02" /><label for="check02">Checkbox2</label></p>


<p><input type='radio' value="male" id="male" name="gender" /> <label for="male">Male</label></p>
<p><input type='radio' value="Female" id="female" name="gender" /> <label for="female">Female</label></p>


<!-- DISABLED -->
<p><input type='checkbox' value="male" disabled /> <label> disabled </label></p>
<p><input type='radio' value="24" name="age" disabled /> <label> disabled</label></p>


<!-- CHECKED DISABLED -->
<p><input type='checkbox' value="male" checked disabled /> <label>checked disabled </label></p>
<p><input type='radio' value="24" name="age" checked disabled /> <label>checked disabled</label></p>

COBRAAzure/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

COBRAAzure/Views/Home/Index.cshtml
@*<div class="body-box">
    <form>
        <div class="flexContainer">
            <div class="divSubHeader">
                Customer Details
            </div>

            <div class="tablebox-border-max400">
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />

                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
            </div>

            <div class="divSubHeader">
                Parent Child Information
            </div>

            <div class="tablebox-border-maxheight">
                Form content
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />

                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />
                Form content<br />

            </div>
        </div>



    </form>
   
</div>*@

<div class="rowSmartLayout">
    <div class="twoCol-1-CellSmartLayout">
        <img src=" @Url.Action("CategoryWiseCustomerReport", "Report")" />  
    </div>
     <div class="twoCol-2-CellSmartLayout">
         <img src=" @Url.Action("ProductWiseContractReport", "Report")" />   
     </div>    
</div>
<div class="rowSmartLayout">
    <div class="twoCol-1-CellSmartLayout">
        <img src=" @Url.Action("ContractStatusSplitupReport", "Report")" />
    </div>
    <div class="twoCol-2-CellSmartLayout">
        <img src=" @Url.Action("RegionWiseBillingReport", "Report")" />
    </div>
</div>