COBRAAzure/Controllers/AdminController.cs
using Entity.AdminModels;
using Entity.UnitOfWork;
using Entity.UnitOfWork.AdminRepo;
using Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace COBRA.MVC
{
    public class AdminController : AdminControllerBase
    {
        public AdminController()
        {
            _uow = new AdminUnitOfWork();
            this._taxRepositoty = new TaxRepository(_uow);
            this._codeListrepositoty = new CodeListDetailRepository(_uow);
        }

        public ActionResult Tax(int? pTaxID)
        {
            try
            {
                Tax tax = null;
                
                if (pTaxID.HasValue
                    && pTaxID.Value > 0)
                {
                    tax = this._taxRepositoty.GetTaxByID(pTaxID.Value); 
                }
                else
                {
                    tax = this._taxRepositoty.CreateTax();
                }

                this.BuildViewBagCollection(tax);
                return View(tax);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Tax(Tax tax)
        {
            try
            {                
                this.ExecutePreSaveConditions<Tax>(tax, this._taxRepositoty, null);

                if (!this.IsModelValid)
                    return View(tax);

                if (tax.RecordVersion == 0) // New Tax
                {
                    this._taxRepositoty.AddTax(tax);
                }
                else
                {
                    this._taxRepositoty.UpdateTax(tax);
                }

                int status = this._taxRepositoty.SaveChanges();
                if (status == ApplicationKeys.SaveUnsucessful)
                {
                    // Save should not unsucessful as the validations are done prior to invoking SaveChanges method 
                    this.BindValidationErrors(tax);
                    return View(tax);
                }
                else
                {
                    return View("_TaxSucess", tax);
                }            
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(tax);
        }

        public ActionResult SearchTax()
        {
            return View(this._taxRepositoty.GetTaxes());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._taxRepositoty.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

COBRAAzure/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entity.ProductModels;
using Entity.UnitOfWork.ProductRepo;
using Entity.UnitOfWork;
using Infrastructure;
using COBRA.Models;
using Grid.Mvc.Ajax.GridExtensions;

namespace COBRA.MVC.Controllers
{
    public class ProductController : ProductControllerBase
    {
        public ProductController(IProductRepository repositoryInstance)
        {
            this._repositoty = repositoryInstance;
        }

        public ProductController()
        {
            _uow = new ProductUnitOfWork();
            this._repositoty = new ProductRepository(_uow);
            this._codeListrepositoty = new CodeListDetailRepository(_uow);
        }

        // GET: /Product/Create
        public ActionResult CreateOrEdit(long? pProductID)
        {
            Product product = null;
            ViewBag.Caption = string.Empty;

            if (!pProductID.HasValue)
            {
                this.BuildViewBagCollection(null);
                return View();
            }
            else if (pProductID.Value == 0)
            {
                product = this._repositoty.CreateProduct();
                ViewBag.Caption = "ADD PRODUCT - " + product.ProductID.ToString();
            }
            else
            {
                product = this._repositoty.GetProductByID(pProductID.Value);
                ViewBag.Caption = "MODIFY PRODUCT - " + product.ProductID.ToString();
            }

            this.BuildViewBagCollection(product);            
            return View(product);                        
        }

        // POST: /Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(Product product)
        {
            try
            {
                this.ExecutePreSaveConditions<Product>(product, this._repositoty, null);                

                if (!this.IsModelValid)
                    return View(product);

                if (product.RecordVersion == 0)
                {
                    this._repositoty.AddProduct(product);
                }
                else
                {
                    product = this._repositoty.UpdateProduct(product);
                }

                int saveStatus = this._repositoty.SaveChanges();

                if (saveStatus != ApplicationKeys.SaveUnsucessful)
                    return View("_ProductSuccess");                

            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(product);         
        }

        public ActionResult Details(long pProductID)
        {
            Product product = this._repositoty.GetProductByID(pProductID);
            return View(product);
        }

        #region Search Products

        public ActionResult SearchProduct()
        {
            return View("Search/_SearchProduct", new ProductSearchCriteriaModel());
        }

        public ActionResult GetDefaultProductSearchResults(ProductSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            AjaxGrid<Product> grid = GetDefaultAjaxGrid<Product>();
            return View(GetProductSearchResultsViewName(searchCriteria), grid);
        }

        public JsonResult GetProductSearchResults(ProductSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Product> grid = GetAjaxGridByList<Product>(this._repositoty.GetProductsBySearchCriteria(searchCriteria));
            return Json(new { Html = grid.ToJson(GetProductSearchResultsViewName(searchCriteria), this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductSearchResultsPaged(ProductSearchCriteriaModel searchCriteria, int? page)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Product> grid = GetAjaxGridByList<Product>(this._repositoty.GetProductsBySearchCriteria(searchCriteria), page.HasValue ? page.Value : 1, 5);
            return Json(new { Html = grid.ToJson(GetProductSearchResultsViewName(searchCriteria), this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Search Discount

        public ActionResult SearchDiscount()
        {
            return View("Search/_SearchDiscount", new DiscountSearchCriteriaModel());
        }
     
        public ActionResult GetDefaultDiscountSearchResults(DiscountSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            AjaxGrid<Discount> grid = GetDefaultAjaxGrid<Discount>();
            return View("Search/_DiscountSearchResults", grid);
        }

        public JsonResult GetDiscountSearchResults(DiscountSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Discount> grid = GetAjaxGridByList<Discount>(this._repositoty.GetDiscountsBySearchCriteria(searchCriteria));
            return Json(new { Html = grid.ToJson("Search/_DiscountSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetDiscountSearchResultsPaged(DiscountSearchCriteriaModel searchCriteria, int? page)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<Discount> grid = GetAjaxGridByList<Discount>(this._repositoty.GetDiscountsBySearchCriteria(searchCriteria), page.HasValue ? page.Value : 1, 5);
            return Json(new { Html = grid.ToJson("Search/_DiscountSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        #endregion


        public ActionResult Discount(int? pDiscountID)
        {
            try
            {
                Discount discount = null;

                if (!pDiscountID.HasValue)
                {
                    return View();
                }
                else if (pDiscountID.Value == 0)
                {
                    discount = this._repositoty.CreateDiscount();                    
                }
                else
                {
                    discount = this._repositoty.GetDiscountByID(pDiscountID.Value);
                }

                base.BuildViewBagCollection(discount);                
                return View(discount);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Discount(Discount discount)
        {
            try
            {
                this.ExecutePreSaveConditions(discount, this._repositoty, discount.DiscountDetailXRefs.ToList());
                
                if (!this.IsModelValid)
                    return View(discount);

                if (discount.RecordVersion == 0)
                    this._repositoty.AddDiscount(discount);
                else
                    this._repositoty.UpdateDiscount(discount);

                int saveStatus = this._repositoty.SaveChanges();

                if (saveStatus == ApplicationKeys.SaveUnsucessful)
                    this.BindValidationErrors(discount);
                else
                    return View("_DiscountSuccess");

            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(discount);
        }

        public ActionResult CreateDiscountDetailXRef(int index)
        {
            try
            {
                DiscountDetailXRef discountDetailXRef = this._repositoty.CreateDiscountDetailXRef();
                ViewData["DiscountDetailXRefIndex"] = index;
                base.BuildViewBagCollection(discountDetailXRef);
                return PartialView("_DiscountDetailXRef", discountDetailXRef);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return PartialView("_DiscountDetailXRef", null);
        }

        public ActionResult DiscountDetails(int pDiscountID)
        {
            Discount discount = this._repositoty.GetDiscountByID(pDiscountID);
            return View(discount);
        }

     
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this._repositoty.Dispose();
            }
            base.Dispose(disposing);
        }

        private string GetProductSearchResultsViewName(ProductSearchCriteriaModel searchCriteria)
        {
            string viewName = "Search/_ProductSearchResults";

            if (searchCriteria.IsContractProductSearch)
            {
                viewName = "Search/_ProductContractSearchResults";
            }
          
            return viewName;
        }
    }
}

COBRAAzure/Views/Shared/_AjaxGridPager.cshtml
@model Grid.Mvc.Ajax.GridExtensions.AjaxGridPager
@if (Model.Pages < 2)
{
    return;
}

<div class="grid-footer">
    <div class="grid-pager">
        <ul class="pagination">
            <li><a href="#" class="grid-prev-page" title="Previous Page" style="display: none"><span class="fa fa-backward"></span></a></li>
            @{if (Model.Pages > Model.PagePartitionSize + 2 &&
                  Model.PagePartitionSize > 0)
            {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                <li><a href="#" class="grid-pageSetLink prev" style="display: none;" data-pageset='1' data-partitionsize="@Model.PagePartitionSize">...</a></li>
                for (int i = 1; i < Model.PagePartitionSize + 1; i++)
                {
                    var currentPage = i + 1;
                    <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                }

                <li><a href="#" class="grid-pageSetLink next" data-pageset='2' data-partitionsize="@Model.PagePartitionSize">...</a></li>
                <li><a href="#" class="grid-page-link" data-page='@Model.Pages'>@Model.Pages</a></li>
            }
            else
            {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                for (int i = 1; i < Model.Pages; i++)
                {
                    var currentPage = i + 1;
                    <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                }
            }
            }
            <li><a href="#" title="Next Page" class="grid-next-page"><span class="fa fa-forward"></span></a></li>
        </ul>
    </div>
</div>

COBRAAzure/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

COBRAAzure/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

COBRAAzure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            COBRA
        </title>    
        @Styles.Render("~/Content/css")            
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/Scripts/jquery-1.10.2.min.js", "~/Scripts/ViewCommonFunc.js", "~/Scripts/ui/jquery-ui.js")
        @Mvc.RazorTools.BundleManager.Styles.Render()
        
        <script src="~/Scripts/qTip/jquery.qtip.js"></script>
        <link href="~/Scripts/qTip/jquery.qtip.css" rel="stylesheet" />
    </head>
    <body>        
       
        <div class="box-shadow">
            <div class="header-box">
                <div class="divLogin">
                    @Html.Partial("_LoginPartial")
                </div>
                <div class="header-banner"></div>

            </div>

            <div>
                @Html.Partial("_Menu")
            </div>

            @RenderBody()

        </div>

        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
                  
        @Scripts.Render("~/bundles/bootstrap")        
        @RenderSection("scripts", required: false)
    </body>
</html>

COBRAAzure/Views/Shared/_LayoutPDF.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>


    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js", "~/Scripts/ViewCommonFunc.js", "~/Scripts/ui/jquery-ui.js")
    @Scripts.Render("~/bundles/jquery.ui")
    @Scripts.Render("~/bundles/jquery.GridMVC")
    @Mvc.RazorTools.BundleManager.Styles.Render()
    
</head>
<body>
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css">
    <link rel="stylesheet" type="text/css" href="~/Scripts/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Gridmvc.css">
    <link rel="stylesheet" type="text/css" href="~/Content/ladda-bootstrap/ladda-themeless.min.css">

    <link href="~/Content/COBRASite.css"  rel="stylesheet" />
    <link href="~/Content/COBRATable.css" rel="stylesheet" />
    <div>
        @*<img src='@Server.MapPath("/Content/Images/HeaderLogo.png")' />*@        
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>

COBRAAzure/Views/Shared/_LayoutSearch.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        COBRA
    </title>
    
    
        @Mvc.RazorTools.BundleManager.Styles.Render()
</head>
<body>    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js", "~/Scripts/ViewCommonFunc.js", "~/Scripts/ui/jquery-ui.js")

    <link href="~/Scripts/themes/base/jquery-ui.css" rel="stylesheet" />

    <script src="~/Scripts/qTip/jquery.qtip.js"></script>
    <link href="~/Scripts/qTip/jquery.qtip.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />    
    <script src="~/Scripts/ui/jquery.ui.core.js"></script>
    <script src="~/Scripts/ui/jquery.ui.widget.js"></script>
    <script src="~/Scripts/ui/jquery.ui.mouse.js"></script>
    <script src="~/Scripts/ui/jquery.ui.button.js"></script>
    <script src="~/Scripts/ui/jquery.ui.draggable.js"></script>
    <script src="~/Scripts/ui/jquery.ui.position.js"></script>
    <script src="~/Scripts/ui/jquery.ui.draggable.js"></script>
    <script src="~/Scripts/ui/jquery.ui.resizable.js"></script>
    <script src="~/Scripts/ui/jquery.ui.dialog.js"></script>
    <script src="~/Scripts/ui/jquery.ui.effect.js"></script>
    <script src="~/Scripts/OpenDialog.js"></script>    
    <script src="/Scripts/app/api.js" type="text/javascript"></script>
    <script src="/Scripts/app/ui.js" type="text/javascript"></script>
    <script src="/Scripts/gridmvc.min.js" type="text/javascript"></script>
    <script src="/Scripts/gridmvc.js" type="text/javascript"></script>
    <script src="~/Scripts/URI.js"></script>
    <script src="~/Scripts/gridmvc-ext.js"></script>        
    <link href="~/Content/ladda-bootstrap/ladda-themeless.min.css" rel="stylesheet" />

    <script src="~/Scripts/ViewCommonFunc.js"></script>
    <div class="background-layout">
        <div class="box-shadow">
            
            <div class="header-box">
                <div class="divLogin">
                    @Html.Partial("_LoginPartial")
                </div>
                <div class="header-banner"></div>
            </div>

            <div>
                @Html.Partial("_Menu")
            </div>

            <div class="body-box">
                @RenderBody()
            </div>           
        </div>
    </div>

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

COBRAAzure/Views/Shared/_Menu.cshtml
<div id="cssCOBRAMenu">
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>
            <a href="#">Customer Management</a>
            <ul>
                <li>@Html.ActionLink("Create", "Registration", "Customer", new { pCustomerID = 0 }, null)</li>
                <li>@Html.ActionLink("View/Edit", "SearchCustomer", "Customer", new { isModalDialog = false }, null)</li>                
            </ul>
        </li>
        <li>
            <a href="#">Product & Pricing</a>
            <ul>
                <li>@Html.ActionLink("Service - Create", "CreateOrEdit", "Service", new { pServiceID = 0 }, null)</li>
                <li>@Html.ActionLink("Service - View/Edit", "SearchService", "Service")</li>
                <li>@Html.ActionLink("Service - Pricing", "PricingDetails", "Service")</li>
                <li>@Html.ActionLink("Service Group - Create", "CreateOrEdit", "ServiceGroup", new { pServiceGroupID = 0 }, null)</li>
                <li>@Html.ActionLink("Service Group - View/Edit", "SearchServiceGroup", "ServiceGroup")</li>
                <li>@Html.ActionLink("Service Group - Pricing", "PricingDetails", "ServiceGroup")</li>
                <li>@Html.ActionLink("Product - Create", "CreateOrEdit", "Product", new { pProductID = 0 }, null)</li>
                <li>@Html.ActionLink("Product - View/Edit", "SearchProduct", "Product")</li>
                <li>@Html.ActionLink("Discount - Create", "Discount", "Product", new { pDiscountID = 0 }, null)</li>
                <li>@Html.ActionLink("Discount - View/Edit", "SearchDiscount", "Product")</li>
            </ul>
        </li>
        <li>
            <a href="#">Order Management</a>
            <ul>
                <li>@Html.ActionLink("Create", "CreateOrEdit", "Contract", new { pContractID = 0, pCustomerID = 0 }, null)</li>
                <li>@Html.ActionLink("View/Edit", "SearchContract", "Contract")</li>
                <li>@Html.ActionLink("Disconnect", "SearchContractByActionType", "Contract", new { pActionType = "Disconnect" }, null)</li>
                <li>@Html.ActionLink("Suspend", "SearchContractByActionType", "Contract", new { pActionType = "Suspend" }, null)</li>
                <li>@Html.ActionLink("Reconnect", "SearchContractByActionType", "Contract", new { pActionType = "Reconnect" }, null)</li>
                <li>@Html.ActionLink("Terminate", "SearchContractByActionType", "Contract", new { pActionType = "Terminate" }, null)</li>
                <li>@Html.ActionLink("Upgrade", "SearchContractByActionType", "Contract", new { pActionType = "Upgrade" }, null)</li>
                <li>@Html.ActionLink("Contract Provisioning", "SearchContractByActionType", "Contract", new { pActionType = "StatusConfirm" }, null)</li>

            </ul>
        </li>
        <li>@Html.ActionLink("Billing", "SearchBilling", "Billing")</li>
        <li>
            <a href="#">Admin</a>
            <ul>
                <li>@Html.ActionLink("Tax", "Tax", "Admin")</li>
            </ul>
        </li>

        <li>@Html.ActionLink("Trouble Ticketing", "OrderManagement", "OrderManagement")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>


</div>