COBRAAzure/Controllers/ServiceGroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Entity.ProductModels;
using Entity.UnitOfWork.ProductRepo;
using Entity.UnitOfWork;
using Infrastructure;
using COBRA.Models;
using Grid.Mvc.Ajax.GridExtensions;

namespace COBRA.MVC.Controllers
{
    public class ServiceGroupController : ServiceGroupControllerBase
    {
        public ServiceGroupController(IServiceGroupRepository repositoryInstance)
        {
            this._repositoty = repositoryInstance;
        }

        public ServiceGroupController()
        {
            _uow = new ProductUnitOfWork();
            this._repositoty = new ServiceGroupRepository(_uow);
            this._codeListrepositoty = new CodeListDetailRepository(_uow);
        }

        // GET: /ServiceGroup/Create
        public ActionResult CreateOrEdit(long? pServiceGroupID)
        {
            try
            {
                ViewBag.Caption = string.Empty;
                ViewBag.SerViceTypeCodeList = new SelectList(this._codeListrepositoty.GetByListName(CodeListKey.ServiceTypeList), "CodeID", "Description");

                if (!pServiceGroupID.HasValue)
                    return View();
                else if (pServiceGroupID.Value == 0)
                {
                    ServiceGroup newServiceGroup = this._repositoty.CreateServiceGroup();
                    ViewBag.Caption = "ADD SERVICE GROUP - " + newServiceGroup.ServiceGroupID.ToString();
                    return View(newServiceGroup);
                }
                else
                {
                    ServiceGroup serviceGroup = this._repositoty.GetServiceGroupByID(pServiceGroupID.Value);
                    ViewBag.Caption = "MODIFY SERVICE GROUP - " + serviceGroup.ServiceGroupID.ToString();
                    return View(serviceGroup);
                }
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View();
        }

        // POST: /ServiceGroup/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateOrEdit(ServiceGroup servicegroup)
        {
            try
            {
                this.ExecutePreSaveConditions(servicegroup, this._repositoty, servicegroup.ServiceGroupDetailXRefs.ToList());
                ViewBag.SerViceTypeCodeList = new SelectList(this._codeListrepositoty.GetByListName(CodeListKey.ServiceTypeList), "CodeID", "Description");

                if (!this.IsModelValid)
                    return View(servicegroup);

                if (servicegroup.RecordVersion == 0)
                {
                    this._repositoty.AddServiceGroup(servicegroup);
                }
                else
                {
                    this._repositoty.UpdateServiceGroup(servicegroup);
                }

                int saveStatus = this._repositoty.SaveChanges();

                if (saveStatus != ApplicationKeys.SaveUnsucessful)
                    return View("_ServiceGroupSuccess");              
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(servicegroup);       
        }

        public ActionResult Details(long pServiceGroupID)
        {
            ServiceGroup serviceGroup = this._repositoty.GetServiceGroupByID(pServiceGroupID);
            return View(serviceGroup);
        }

        #region Search Service Groups

        public ActionResult SearchServiceGroup()
        {
            return View("Search/_SearchServiceGroup", new ServiceGroupSearchCriteriaModel());
        }

        public ActionResult GetDefaultSearchResults(ServiceGroupSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;
            AjaxGrid<ServiceGroup> grid = GetDefaultAjaxGrid<ServiceGroup>();
            return View("Search/_ServiceGroupSearchResults", grid);
        }

        public JsonResult GetSearchResults(ServiceGroupSearchCriteriaModel searchCriteria)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<ServiceGroup> grid = GetAjaxGridByList<ServiceGroup>(this._repositoty.GetServiceGroupsBySearchCriteria(searchCriteria));
            return Json(new { Html = grid.ToJson("Search/_ServiceGroupSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSearchResultsPaged(ServiceGroupSearchCriteriaModel searchCriteria, int? page)
        {
            ViewBag.IsModalDialog = searchCriteria.IsModalDialog;

            AjaxGrid<ServiceGroup> grid = GetAjaxGridByList<ServiceGroup>(this._repositoty.GetServiceGroupsBySearchCriteria(searchCriteria), page.HasValue ? page.Value : 1, 5);
            return Json(new { Html = grid.ToJson("Search/_ServiceGroupSearchResults", this), grid.HasItems }, JsonRequestBehavior.AllowGet);
        }

        #endregion
    
        public ActionResult CreateServiceGroupDetailXRef(int index)
        {
            try
            {
                ServiceGroupDetailXRef svcGruoupDetailXRef = this._repositoty.CreateServiceGroupDetailXRef();
                ViewData["ServiceGroupDetailXRefIndex"] = index;
                return PartialView("_ServiceGroupDetail", svcGruoupDetailXRef);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return PartialView("_ServiceGroupDetail", null);
        }

        public ActionResult PricingDetails(long? pServiceGroupID, int? pContractTermTypeCodeID)
        {
            try
            {
                ServiceGroupPricing serviceGroupPricing = null;
                ServiceGroup serviceGroup = null;
                
                if (!pServiceGroupID.HasValue
                    || !pContractTermTypeCodeID.HasValue)
                {
                    serviceGroupPricing = new ServiceGroupPricing();
                    serviceGroupPricing.ServiceGroupID = pServiceGroupID.HasValue ? pServiceGroupID.Value : 0;
                    this._repositoty.ExecuteBusinessRules(serviceGroupPricing, BusinessRulesActionTypeEnum.ObjectMaterialize, string.Empty);                  
                    base.BuildViewBagCollection(serviceGroupPricing);
                    return View(serviceGroupPricing);
                }

                
                serviceGroup = this._repositoty.GetServiceGroupByID(pServiceGroupID.Value);
                serviceGroupPricing = serviceGroup.CurrentServiceGroupPricing(pContractTermTypeCodeID.Value);
                if (serviceGroupPricing == null)
                {
                    serviceGroupPricing = this._repositoty.CreateServiceGroupPricing();
                    serviceGroupPricing.ServiceGroupID = serviceGroup.ServiceGroupID;                    
                    serviceGroupPricing.ContractTermTypeCodeID = pContractTermTypeCodeID.Value;
                }

                serviceGroupPricing.ServiceGroup = serviceGroup;
                this._repositoty.AddCalculatedServiceGroupPricingDetails(serviceGroupPricing);

                // The business rules are to be executed explicitly as few of ServicePricingDetailXRef
                // objects in the collection are manually added(neither created through factory class nor loaded from database)
                // and hence the business rules are not be executed automatically.
                // Note: Business rules are configured to execute automatically if the object is either created through repository create method 
                // OR loaded from the database triggering ObjectMaterialize event
                this._repositoty.ExecuteBusinessRules(serviceGroupPricing, BusinessRulesActionTypeEnum.ObjectMaterialize, string.Empty);
                
                base.BuildViewBagCollection(serviceGroupPricing);
                return View(serviceGroupPricing);
            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PricingDetails(ServiceGroupPricing serviceGroupPricing)
        {            
            try
            {
                this.ExecutePreSaveConditions<ServiceGroupPricing>(serviceGroupPricing, this._repositoty, null);

                if (!this.IsModelValid)
                    return View(serviceGroupPricing);

                this._repositoty.UpdateServiceGroupPricingDetails(serviceGroupPricing);
                int saveStatus = this._repositoty.SaveChanges();

                if (saveStatus != ApplicationKeys.SaveUnsucessful)
                    return View("_ServiceGroupSuccess");                

            }
            catch (Exception ex)
            {
                ExceptionHandlingManager.Instance.HandleException(ex, ExceptionPolicyName.Controller);
            }

            return View(serviceGroupPricing);           
        }

        public ActionResult PricingDetailXRefList(long pserviceGroupID, int pContractTermTypeCodeID, int? pVersion)
        {
            ServiceGroup serviceGroup = this._repositoty.GetServiceGroupByID(pserviceGroupID);
            ServiceGroupPricing currentServiceGroupPricing = null;

            if (pVersion.HasValue)
            {

COBRAAzure/Views/ServiceGroup/CreateOrEdit.cshtml
@model Entity.ProductModels.ServiceGroup

@{
    ViewBag.Title = "Create ServiceGroup";
    Layout = "~/Views/Shared/_LayoutSearch.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="flexContainer">
        @Html.ValidationSummary(true)
        @Html.GenerateHiddenControlsForReadOnly(Model)
        @Html.Hidden("ServiceGroupIndex", Model == null ? 0 : Model.ServiceGroupDetailXRefs.Count)

        @Html.Hidden("hdnSearchResult")
        @{
            bool isReadOnly = false;

            if (Model == null)
            {
                isReadOnly = true;
            }
        }

        <div class="divSubHeader">
            Service Group
        </div>

        <div class="tablebox-border-max400">
            <div class="rowSmartLayout">
                <div class="twoCol-1-CellSmartLayout">
                    <div class="CellLabel">
                        @Html.LabelFor(model => model.ServiceGroupID, "Service Group ID")
                    </div>
                    <div class="CellControl">
                        @Html.CustomEditorFor(model => model.ServiceGroupID, true)
                        @Html.ValidationMessageFor(model => model.ServiceGroupID)
                    </div>
                </div>
            </div>

            <div class="rowSmartLayout">
                <div class="twoCol-1-CellSmartLayout">
                    <div class="CellLabel">
                        @Html.LabelFor(model => model.Name, "Name")
                    </div>
                    <div class="CellControl">
                        @Html.CustomEditorFor(model => model.Name, isReadOnly)
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
            </div>

            <div class="rowSmartLayout">
                <div class="twoCol-1-CellSmartLayout">
                    <div class="CellLabel">
                        @Html.LabelFor(model => model.Description, "Description")
                    </div>
                    <div class="CellControl">
                        @Html.CustomEditorFor(model => model.Description, isReadOnly)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>
            </div>
        </div>

        <div class="divSubHeader">
            Service(s)
        </div>

        <div id="divServiceGroupDetailList" class="tablebox-border-maxheight">
            <div>
                @if (Model != null && Model.HasServiceGroupPricing)
                {
                    <button name="btnServiceGroupDetailLNew" id="btnServiceGroupDetailLNew" type="button" disabled><i class="fa fa-plus"></i>  Service</button>
                }
                else
                {
                    <button name="btnServiceGroupDetailLNew" id="btnServiceGroupDetailLNew" type="button"><i class="fa fa-plus"></i>  Service</button>
                }
            </div>
            <table class="htmlTable-css" id="tableServiceGroupDetailXrefs" style="text-align:left;">
                <thead>
                    <tr>
                        <th>
                            Service Name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        ViewData.Add("ServiceGroupDetailXRefIndex", 0);
                        if (Model != null)
                        {
                            List<Entity.ProductModels.ServiceGroupDetailXRef> groupDetailXRefList = Model.ServiceGroupDetailXRefs.ToList();
                            for (int index = 0; index < groupDetailXRefList.Count; index++)
                            {
                                ViewData["ServiceGroupDetailXRefIndex"] = index;
                                Html.RenderPartial("_ServiceGroupDetail", groupDetailXRefList[index]);
                            }
                        }
                    }
                </tbody>
            </table>
        </div>

        <div class="divButton-right">
            <button name="btnsave" type="submit"><i class="fa fa-save"></i>  Save</button>
        </div>
     
    </div>
        
        }

        @{
            // This is to initiate Service search as Modal Dialog
            COBRA.Models.ServiceSearchCriteriaModel searchModel = new COBRA.Models.ServiceSearchCriteriaModel();
            searchModel.IsModalDialog = true;
            Html.RenderPartial("Search/_SearchService", searchModel);
        }


        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ViewCommonFunc.js")

            <script language="javascript">

                HideDeletedServiceDetailGroupXRef();

                $("#btnServiceGroupDetailLNew").click(function () {
                    var tempUrl = '@Url.Action("CreateServiceGroupDetailXRef", "ServiceGroup")';
                    CreateNewTableRowByIndex("tableServiceGroupDetailXrefs", tempUrl, "ServiceGroupIndex");

                    @*var currentIndex = 0;

                    $("#tableServiceGroupDetailXrefs tr").each(function (index, value) {
                        currentIndex++;
                    });
                    currentIndex = currentIndex - 2;
                    var tempUrl = '@Url.Action("CreateServiceGroupDetailXRef", "ServiceGroup")';
                    var postData = { index: currentIndex };
                    $.ajax({
                        async: false,
                        cache: false,
                        url: tempUrl,
                        data: postData,
                        success: function (data) {

                            $("#tableServiceGroupDetailXrefs tbody").append("'" + data + "'");

                        },
                        error: function (errorThrown) {
                            $(divToLoad).html(errorThrown.responseText);
                            alert(errorThrown.responseText);
                        }
                    });*@
                });

                function DeleteServiceDetailGroupXRef(selectedIndex) {
                    $("#tableServiceGroupDetailXrefs tbody").find("tr").each(function (index, value) {

                        if (selectedIndex == index) {
                            $(this).hide();
                            $("#ServiceGroupDetailXRefs_" + selectedIndex + "__RecordStatus").val(false);
                        }
                    });
                }

                function HideDeletedServiceDetailGroupXRef() {
                    $("#tableServiceGroupDetailXrefs tbody").find("tr").each(function (index, value) {
                        if ($("#ServiceGroupDetailXRefs_" + index + "__RecordStatus").val().toLowerCase() == "false") {
                            $(this).hide();
                        }
                    });
                }

         
                function SearchService(index) {
                    OpenServiceSearchDialog();
                    $("#hdnSearchResult").val(index);
                }

                function RefreshService(tempServiceID, tempServiceDesc) {
                    var index = $("#hdnSearchResult").val();
                    var objID = $("#ServiceGroupDetailXRefs_" + index + "__ServiceID");
                    var objName = $("#ServiceGroupDetailXRefs_" + index + "__ServiceName");
                    objID.val(tempServiceID);
                    objName.val(tempServiceDesc);
                    CloseServiceSearchDialog();
                }

            </script>
        }

COBRAAzure/Views/ServiceGroup/Details.cshtml
@model Entity.ProductModels.ServiceGroup
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.ServiceGroupID</h2>
<h2>Details</h2>

COBRAAzure/Views/ServiceGroup/PricingDetails.cshtml
@model Entity.ProductModels.ServiceGroupPricing
@{
    ViewBag.Title = "Update Pricing Details";
    Layout = "~/Views/Shared/_LayoutSearch.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="flexContainer">
        @Html.ValidationSummary(true)
        @Html.ValidationMessageFor(model => model.ServiceGroupPricingID)
        @Html.GenerateHiddenControlsForReadOnly(Model)

        @{
            bool isReadOnly = false;
            if (Model == null)
            {
                isReadOnly = true;
            }

            Html.AddCustomHTMLAttributes(model => model.ContractTermTypeCodeID, "onchange", "LoadPricingDetails();");
        }


        <div class="divSubHeader">
            Service Group Pricing Information
        </div>

        <div class="tablebox-border-max400">
            <div class="rowSmartLayout">
                <div class="twoCol-1-CellSmartLayout">
                    <div class="CellLabel">
                        @Html.Label("lbServiceGroup", "Service Group")
                    </div>
                    <div class="CellControl">
                        @Html.TextBox("ServiceGroupName", (string)ViewBag.ServiceGroupName, new { @readonly = "readonly" })                        
                        @Html.ValidationMessageFor(model => model.ServiceGroupPricingID)
                        @Html.ValidationMessageFor(model => model.ServiceGroupID)
                        <button name="btnSearchGroup" id="btnSearchGroup" type="button" onclick="OpenSearchServiceGroups();"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>

            <div class="rowSmartLayout">
                <div class="twoCol-1-CellSmartLayout">
                    <div class="CellLabel">
                        @Html.LabelFor(model => model.ContractTermTypeCodeID, "Contract Term")
                    </div>
                    <div class="CellControl">
                        @Html.CustomDropDownFor(model => model.ContractTermTypeCodeID, Model)
                        @Html.ValidationMessageFor(model => model.ContractTermTypeCodeID)
                    </div>
                </div>
            </div>

            @if (Model != null && Model.ServiceGroupPricingID > 0)
            {
                <div class="rowSmartLayout">
                    <div class="twoCol-1-CellSmartLayout">
                        <div class="CellLabel">
                            @Html.LabelFor(model => model.EffectiveDate, "Effective Date")
                        </div>
                        <div class="CellControl">
                            @Html.CustomEditorFor(model => model.EffectiveDate, false)
                            @Html.ValidationMessageFor(model => model.EffectiveDate)
                        </div>
                    </div>
                </div>
            }
        </div>

        <div class="divSubHeader">
            Service Group Pricing Details
        </div>


        <div id="divServiceGroupPricingDetailsList" class="tablebox-border-maxheight">      
            <div>
               
            </div>    
            <table class="htmlTable-css" id="tableServiceGroupPricingDetailXrefs">
                <thead>
                    @if (Model != null && Model.Version > 0)
                    {
                        <tr>
                            <td>Version : @Model.Version</td>
                        </tr>
                    }

                    <tr>
                        <th>

                        </th>
                        <th>
                            Category
                        </th>
                        <th>
                            State
                        </th>
                        <th>
                            City
                        </th>
                        <th>
                            Region
                        </th>
                        <th>
                            Subscription Charges
                        </th>
                        <th>
                            OneTime Charges
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        ViewData.Add("ServiceGroupPricingDetailXRefIndex", 0);
                        if (Model != null)
                        {
                            List<Entity.ProductModels.ServiceGroupPricingDetailXRef> serviceGroupPricingDetailXRefList = Model.ServiceGroupPricingDetailXRefs.ToList()
                                .OrderBy(detail => detail.OrderedPricingGroupKey)
                                .ThenBy(detail => detail.ServiceID)
                                .ToList();

                            string groupIdentifier = string.Empty;
                            int serviceCount = (int)ViewBag.ServiceCount;

                            for (int index = 0; index < serviceGroupPricingDetailXRefList.Count; index++)
                            {
                                string tempGroupIdentifier = serviceGroupPricingDetailXRefList[index].PricingGroupKey;
                                if (string.IsNullOrEmpty(groupIdentifier)
                                    || groupIdentifier != tempGroupIdentifier)
                                {
                                    bool isActive = serviceGroupPricingDetailXRefList[index].RecordStatus;
                                    <tr>
                                        <td>
                                            @if (isActive)
                                            {
                                                <input type="checkbox" id="chkSelectPricing_@index" onchange="RemovePricingDetails('@index', '@serviceCount');" checked />
                                            }
                                            else
                                            {
                                                <input type="checkbox" id="chkSelectPricing_@index" onchange="RemovePricingDetails('@index', '@serviceCount');" />
                                            }
                                        </td>
                                        <td>
                                            @serviceGroupPricingDetailXRefList[index].CategoryCode.Description
                                        </td>
                                        <td>
                                            @serviceGroupPricingDetailXRefList[index].ServiceArea.StateCode.Description
                                        </td>
                                        <td>
                                            @serviceGroupPricingDetailXRefList[index].ServiceArea.CityCode.Description
                                        </td>
                                        <td>
                                            @serviceGroupPricingDetailXRefList[index].ServiceArea.RegionCode.Description
                                        </td>
                                        <td></td>
                                        <td></td>
                                    </tr>

                                                <tr>
                                                    <th>

                                                    </th>
                                                    <th>
                                                        Service ID
                                                    </th>
                                                    <th colspan="3">
                                                        Service Description
                                                    </th>
                                                    <th>

                                                    </th>
                                                    <th>

                                                    </th>
                                                </tr>

                                    groupIdentifier = tempGroupIdentifier;
                                }

                                ViewData["ServiceGroupPricingDetailXRefIndex"] = index;
                                Html.RenderPartial("_PricingDetailXRef", serviceGroupPricingDetailXRefList[index]);
                            }
                        }
                    }

                </tbody>
            </table>          
        </div>

        <div class="divButton-right">
            <button name="btnsave" type="submit"><i class="fa fa-save"></i>  Save</button>
        </div>
    </div>    
}

@{
    // This is to initiate Service search as Modal Dialog
    COBRA.Models.ServiceGroupSearchCriteriaModel searchModel = new COBRA.Models.ServiceGroupSearchCriteriaModel();
    searchModel.IsModalDialog = true;
    Html.RenderPartial("Search/_SearchServiceGroup", searchModel);
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


    <script language="javascript">
       
        function OpenSearchServiceGroups() {
            OpenServiceGroupSearchDialog();
        }

        function RefreshServiceGroup(tempServiceGroupID, tempServiceGroup) {

            $("#ServiceGroupID").val(tempServiceGroupID);
            $("#ServiceGroupName").val(tempServiceGroup);

            CloseServiceGroupSearchDialog();

            var tempContractTermTypeCodeID = $("#ContractTermTypeCodeID").val();
            if (tempContractTermTypeCodeID > 0) {
                LoadPricingDetails();
            }
        }

        function LoadPricingDetails() {
            var tempServiceGroupID = $("#ServiceGroupID").val();

            if (tempServiceGroupID <= 0) {
                alert("Please select Service Group!!");
                return;
            }

            var tempContractTermTypeCodeID = $("#ContractTermTypeCodeID").val();
            var tempUrl = '@Html.Raw(Url.Action("PricingDetails", "ServiceGroup", new { pServiceGroupID = -111, pContractTermTypeCodeID = -222 }))';
            tempUrl = tempUrl.replace("-111", tempServiceGroupID);
            tempUrl = tempUrl.replace("-222", tempContractTermTypeCodeID);
            location.href = tempUrl;
        }

        function RemovePricingDetails(index, serviceCount)
        {
            if ($("#chkSelectPricing_" + index).is(':checked')) {
                for (var currentIndex = index; currentIndex < index + serviceCount; currentIndex++)
                    $("#ServiceGroupPricingDetailXRefs_" + currentIndex + "__RecordStatus").val(true);
            }
            else {
                for (var currentIndex = index; currentIndex < index + serviceCount; currentIndex++)
                    $("#ServiceGroupPricingDetailXRefs_" + currentIndex + "__RecordStatus").val(false);
            }
        }        
</script>
}

COBRAAzure/Views/ServiceGroup/_PricingDetailXRef.cshtml
@model Entity.ProductModels.ServiceGroupPricingDetailXRef


@{
    Layout = null;
}

@{
    int index = 0;
    if (ViewData["ServiceGroupPricingDetailXRefIndex"] != null)
    {
        index = (int)ViewData["ServiceGroupPricingDetailXRefIndex"];
    }    
}

<tr id="ServiceGroupPricingDetailXRefRow@(index)">
   
    @Html.GenerateHiddenControlsForReadOnly(Model, index)
    <td>
        
    </td>
    <td>
        <div class="form-group">
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ServiceID)
            </div>
        </div>
    </td>
    <td colspan="3">    
        <div class="form-group">
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Service.Description)
            </div>
        </div>    
    </td>   
    <td>
        <div class="form-group">
            <div class="col-md-10">
                @Html.CustomEditorFor(model => model.SubscriptionCharges, false, index)
                @Html.CustomValidationMessageFor(model => model.SubscriptionCharges, index)
            </div>
        </div>
    </td>
    <td>
        <div class="form-group">
            <div class="col-md-10">
                @Html.CustomEditorFor(model => model.OneTimeCharges, false, index)
                @Html.CustomValidationMessageFor(model => model.OneTimeCharges, index)            
            </div>
        </div>


    </td>
</tr>

COBRAAzure/Views/ServiceGroup/_ServiceGroupDetail.cshtml
@model Entity.ProductModels.ServiceGroupDetailXRef


@{
    Layout = null;
}

    @{
        int index = 0;
        if (ViewData["ServiceGroupDetailXRefIndex"] != null)
        {
            index = (int)ViewData["ServiceGroupDetailXRefIndex"];
        }

        string idPrefix = Html.GetModelPrefix(Model, index) ;    
    }


<tr id="serviceGroupDetailXRefRow@(index)">
    <td>

        @Html.GenerateHiddenControlsForReadOnly(Model, index)
        
        @Html.TextBox(idPrefix + "ServiceName", (Model == null || Model.Service == null) ? string.Empty : Model.Service.Description, new { @readonly = "readonly" })
        @Html.CustomValidationMessageFor(model => model.ServiceID, index)
        @if (Model != null && !Model.CanWrite)
        {
            <button name="btnSearchService" id="btnSearchService" type="button" disabled><i class="fa fa-search"></i></button>
            <button name="btnDelete" id="btnDelete" type="button" disabled><i class="fa fa-trash"></i></button>
        }
        else
        {
            <button name="btnSearchService" id="btnSearchService" type="button" onclick="SearchService(@index);" ><i class="fa fa-search"></i></button>
            <button name="btnDelete" id="btnDelete" type="button" onclick="DeleteServiceDetailGroupXRef(@index);"><i class="fa fa-trash"></i></button>            
        }   
    </td>
</tr>

COBRAAzure/Views/ServiceGroup/_ServiceGroupSuccess.cshtml
@model Entity.ProductModels.ServiceGroup

@{
    ViewBag.Title = "Success";
}

<h1 class="text-danger">ServiceGroup Successfully Saved</h1>